### ISSUE TITLE
Разобраться почему от сервера иногда приходит 404.

### ISSUE THREAD

**Issue by AndreySmirdin** [AndreySmirdin/Wall-et#3]
При запросах добавления/обновления магазина иногда приходит 404 от сервера. Понять в чем проблема. По результатам обязательно отписаться в этот тикет.
Примеры 404-ок можно найти в наших логах.

**Comment by oquechy** [comment]
Укажите браузер и ОС. Не удаётся воспроизвести...

**Comment by AndreySmirdin** [comment]
На сколько я знаю примеры есть как для Хрома так и для Сафари

**Comment by Igor-Tukh** [comment]
Получилось воспроизвести данную ошибку.
Похоже, все дело в корявой обработке ошибки, возникающей из-за задержки во время работы сборщика мусора.
Будет исправлено.

**Comment by Igor-Tukh** [comment]
Исправлено, ушло в тестинг.

**Comment by oquechy** [comment]
Поправь ещё опечатку в названии теста... Остальное хорошо, закрываю.
