### ISSUE TITLE
Добавить Яндекс.Деньги как новый источник получения кешбека.

### ISSUE THREAD

**Issue by AndreySmirdin** [AndreySmirdin/Wall-et#4]

**Comment by oquechy** [comment]
Беру себе

**Comment by AndreySmirdin** [comment]
Помимо денег требуется добавить еще Qiwi.

**Comment by oquechy** [comment]
Ок, чекни как Яндекс.Деньги работают

**Comment by oquechy** [comment]
Добавила тесты

**Comment by AndreySmirdin** [comment]
Код посмтрел, выглядит разумно. Но тест все равно надо написать:)

**Comment by AndreySmirdin** [comment]
Тесты увидел, можно мерджить.

**Comment by oquechy** [comment]
Посмотри киви

**Comment by AndreySmirdin** [comment]
Посмотрел. Вижу слишком много дублирования кода. Попробуй вынести какой-нибудь абстрактный класс Payment.

**Comment by oquechy** [comment]
Вынесла интерфейс 🙄

**Comment by AndreySmirdin** [comment]
Ага, супер. Можно мерджить.
