### ISSUE TITLE
При переключении между экранами в приложении под Android пользовательский интерфейс подтормаживает.

### ISSUE THREAD

**Issue by Igor-Tukh** [AndreySmirdin/Wall-et#8]

**Comment by AndreySmirdin** [comment]
Взял в работу. Хочу воспроизвести у себя.
Какая версия андроида используется? Межу какими экранами переключение?

**Comment by Igor-Tukh** [comment]
Сообщение от клиента
> Android 6.0, версия приложения 0.1.239 
> Эта неприятность проявляется при следующей последовательности действий:
> * Открываем приложение
> * Заходим во вкладку счет
> * Возвращаемся на базовый экран
> * Повторяем последние два действия 30 раз
> * На 31 раз ВСЕ ТОРМОЗИТ, Я ТАК НЕ МОГУ, ПОФИКСИТИ ПЛИЗ, ПРОГРАММИСТЫ ЗА ЧТО ДЕНЬГИ У ВАС ПОЛУЧАЮТ!!!1!

**Comment by AndreySmirdin** [comment]
Окей, понял. Скорее всего просто создается каждый раз новое активити.

**Comment by AndreySmirdin** [comment]
Написал на это юнит-тест, закономерно, что он пока не проходит.

**Comment by AndreySmirdin** [comment]
Все реализовал, выкатится в новом релизе.
